name-template: $NEXT_PATCH_VERSION 🌈
tag-template: $NEXT_PATCH_VERSION
template: |
  # What's Changed
  
  $CHANGES
categories:
  - title: ⚠️ Breaking API changes
    label: breaking-api-change

  - title: 🚀 Features & Enhancements
    labels:
      - feature
      - enhancement

  - title: ☠️ Deprecations
    label: deprecation

  - title: 🐛 Bug Fixes
    # The label is the bug not the bug
    label: bug

  - title: 📖 Documentation
    label: docs

  - title: 🧹 Housekeeping
    labels:
      - housekeeping
      - test-improvement

  - title: 📦 Dependency updates
    label: dependencies
    collapse-after: 5