services:
  database:
    image: 'mysql:8.2.0'
    container_name: database
    hostname: database
    environment:
      MYSQL_DATABASE: ${DATABASE_DB}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - ${DATABASE_EXPOSE_PORT}:3306
    volumes:
      - ${DATABASE_INIT}:/docker-entrypoint-initdb.d
      - ${DATABASE_STORE}:/var/lib/mysql
    restart: always