blank_issues_enabled: false
contact_links:
  - name: Need help or have a question?
    url: https://github.com/mcddhub/mcdd-spring-boot-study/discussions/
    about: Visit our slack channel.
  - name: Have a question or want to drive a Community conversation?
    url: https://github.com/mcddhub/mcdd-spring-boot-study/discussions/
    about: Visit our Discussions page.
