server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo03-test
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  sql:
    init:
      schema-locations: classpath*:db/schema.sql
      data-locations: classpath*:db/data.sql

